### ISSUE TITLE
Found input variables with inconsistent numbers of samples: [1, 512]

### ISSUE THREAD

**Issue by TFMasterFlowHub** [Niranjankumar-c/Perceptron_Model#2]
ValueError                                Traceback (most recent call last)
<ipython-input-66-140f1c53ae4b> in <module>
----> 1 wt_matrix = perceptron.fit(X_train, Y_train, 10000, 0.3)

<ipython-input-64-7300154960e6> in fit(self, X, Y, epochs, lr)
     37             wt_matrix.append(self.w)
     38 
---> 39             accuracy[i] = accuracy_score(self.predict(X), Y)
     40             if (accuracy[i] > max_accuracy):
     41                 max_accuracy = accuracy[i]

~\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py in accuracy_score(y_true, y_pred, normalize, sample_weight)
    183 
    184     # Compute accuracy for each possible representation
--> 185     y_type, y_true, y_pred = _check_targets(y_true, y_pred)
    186     check_consistent_length(y_true, y_pred, sample_weight)
    187     if y_type.startswith('multilabel'):

~\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py in _check_targets(y_true, y_pred)
     78     y_pred : array or indicator matrix
     79     """
---> 80     check_consistent_length(y_true, y_pred)
     81     type_true = type_of_target(y_true)
     82     type_pred = type_of_target(y_pred)

~\Anaconda3\lib\site-packages\sklearn\utils\validation.py in check_consistent_length(*arrays)
    210     if len(uniques) > 1:
    211         raise ValueError("Found input variables with inconsistent numbers of"
--> 212                          " samples: %r" % [int(l) for l in lengths])
    213 
    214 

ValueError: Found input variables with inconsistent numbers of samples: [1, 512]

**Comment by Niranjankumar-c** [comment]
Hi, 
The issue occurred because of the indexation problem in the `predict` function. Fixed now.

**Comment by Niranjankumar-c** [comment]
Hence, 
Closing the issue now.
